### ISSUE TITLE
Error	C1083	Cannot open include file: 'qwidgetresizehandler_p.h': No such file or directory

### ISSUE THREAD

**Issue by jaan-hou** [FreedomZZQ/IcePlayer#2]
VS2015+Qt5.5

请问你Qt具体的版本是哪个呢？在新版本中，qwidgetresizehandler_p.h的内容可能改变了，这是私有的API。

**Comment by FreedomZZQ** [comment]
你好，当时的开发环境是VS2013+Qt5.3.1 x64
确实是强行调用的私有API，主要是用于实现窗体拖拽，可以使用其他方法替换

**Comment by jaan-hou** [comment]
谢谢

**Comment by fanyer** [comment]
qt5.71  msvc2015
you may defined and realize drag and drop events by yourself.  Both IcePlayer and mini need to do this.
like below
```
QPoint move_point; 
bool mouse_press; 

void mousePressEvent(QMouseEvent *event);
void mouseReleaseEvent(QMouseEvent *event);
void mouseMoveEvent(QMouseEvent *event);
```
